from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer


ChatBot = ChatBot("ChatFutBot")

trainer = ListTrainer(ChatBot)
trainer.train([

"Quais times participaram do campeonato de 2023?",
"Os seguintes clubes participaram da edicao de 2023:Athletico Paranaense, Operário, Coritiba, Maringá, Cianorte, FC Cascavel, Aruko SB, São-Joseense, Azuriz, Londrina, Rio Branco e Foz do Iguaçu",       
"Quais times participaram do campeonato de 2022?",
"Os seguintes clubes participaram da edicao de 2022:Operário, Coritiba, Athletico Paranaense, Maringá, FC Cascavel, Londrina, Cianorte, São-Joseense, Rio Branco, Azuriz, União e Paraná",
"Quais times participaram do campeonato de 2022?",
"Os seguintes clubes participaram da edicao de 2022:Operário, FC Cascavel, Athletico Paranaense, Cianorte, Londrina, Paraná, Maringá, Azuriz, Coritiba, Rio Branco, Toledo e Cascavel CR",
"Quais times participaram do campeonato de 2020?",
"Os seguintes clubes participaram da edicao de 2020:Coritiba, FC Cascavel, Athletico Paranaense, Operário, Cianorte, Londrina, Rio Branco, Paraná, Cascavel CR, Toledo, PSTC e União",
"Quais times participaram do campeonato de 2019?",
"Os seguintes clubes participaram da edicao de 2019:Toledo, FC Cascavel, Operário, Coritiba, Maringá, Paraná, Londrina, Cianorte, Athletico Paranaense, Cascavel CR, Foz do Iguaçu e Rio Branco",
"Quais times participaram do campeonato de 2018?",
"Os seguintes clubes participaram da edicao de 2018:Foz do Iguaçu, Athletico Paranaense, Coritiba, Rio Branco, FC Cascavel, Londrina, Cianorte, Toledo, Maringá, União, Paraná e Prudentópolis",
"Quais times participaram do campeonato de 2017?",
"Os seguintes clubes participaram da edicao de 2017:Paraná, Coritiba, Cianorte, Londrina, Prudentópolis, FC Cascavel, Athletico Paranaense, Rio Branco, Foz do Iguaçu, Toledo, PSTC e J.Malucelli",        
"Quais times participaram do campeonato de 2016?",
"Os seguintes clubes participaram da edicao de 2016:Paraná, J.Malucelli, Coritiba, Athletico Paranaense, Londrina, Toledo, PSTC, Foz do Iguaçu, FC Cascavel, Rio Branco, Operário e Maringá",
"Quais times participaram do campeonato de 2015?",
"Os seguintes clubes participaram da edicao de 2015:Coritiba, J.Malucelli, Operário, Maringá, Londrina, Paraná, Foz do Iguaçu, FC Cascavel, Athletico Paranaense, Rio Branco, Nacional AC e Prudentópolis",
"Quais times participaram do campeonato de 2014?",
"Os seguintes clubes participaram da edicao de 2014:Paraná, Coritiba, Maringá, Londrina, J.Malucelli, Prudentópolis, Rio Branco, Athletico Paranaense, Cianorte, Operário, Arapongas EC e Toledo",
"Quais times participaram do campeonato de 2013?",
"Os seguintes clubes participaram da edicao de 2013:Coritiba, Londrina, Paraná, J.Malucelli, Athletico Paranaense, Arapongas EC, AC Paranavai, Toledo, Operário, Cianorte, Rio Branco e Nacional AC",
"Quais times participaram do campeonato de 2012?",
"Os seguintes clubes participaram da edicao de 2012:Athletico Paranaense, Coritiba, Cianorte, Arapongas EC, Toledo, Rio Branco, Londrina, J.Malucelli, Roma Apucarana, Operário, AC Paranavai e Iraty SC",  
"Em que posição o Athletico Paranaense ficou em 2023?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",      
"Em que posição o Operário ficou em 2023?",
"Na primeira fase ficou em 2 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",      
"Em que posição o Coritiba ficou em 2023?",
"Na primeira fase ficou em 3 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Maringá ficou em 2023?",
"Na primeira fase ficou em 4 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",      
"Em que posição o Cianorte ficou em 2023?",
"Na primeira fase ficou em 5 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o FC Cascavel ficou em 2023?",
"Na primeira fase ficou em 6 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o Aruko SB ficou em 2023?",
"Na primeira fase ficou em 7 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o São-Joseense ficou em 2023?",
"Na primeira fase ficou em 8 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Azuriz ficou em 2023?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Londrina ficou em 2023?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o Rio Branco ficou em 2023?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o Foz do Iguaçu ficou em 2023?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Em que posição o Operário ficou em 2022?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Coritiba ficou em 2022?",
"Na primeira fase ficou em 2 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",
"Em que posição o Athletico Paranaense ficou em 2022?",
"Na primeira fase ficou em 3 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Maringá ficou em 2022?",
"Na primeira fase ficou em 4 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o FC Cascavel ficou em 2022?",
"Na primeira fase ficou em 5 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Londrina ficou em 2022?",
"Na primeira fase ficou em 6 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Cianorte ficou em 2022?",
"Na primeira fase ficou em 7 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o São-Joseense ficou em 2022?",
"Na primeira fase ficou em 8 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Rio Branco ficou em 2022?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Azuriz ficou em 2022?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o União ficou em 2022?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o Paraná ficou em 2022?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Em que posição o Operário ficou em 2022?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o FC Cascavel ficou em 2022?",
"Na primeira fase ficou em 2 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o Athletico Paranaense ficou em 2022?",
"Na primeira fase ficou em 3 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Cianorte ficou em 2022?",
"Na primeira fase ficou em 4 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Londrina ficou em 2022?",
"Na primeira fase ficou em 5 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",
"Em que posição o Paraná ficou em 2022?",
"Na primeira fase ficou em 6 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Maringá ficou em 2022?",
"Na primeira fase ficou em 7 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Azuriz ficou em 2022?",
"Na primeira fase ficou em 8 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Coritiba ficou em 2022?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Rio Branco ficou em 2022?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o Toledo ficou em 2022?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o Cascavel CR ficou em 2022?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Em que posição o Coritiba ficou em 2020?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o FC Cascavel ficou em 2020?",
"Na primeira fase ficou em 2 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Athletico Paranaense ficou em 2020?",
"Na primeira fase ficou em 3 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",
"Em que posição o Operário ficou em 2020?",
"Na primeira fase ficou em 4 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Cianorte ficou em 2020?",
"Na primeira fase ficou em 5 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Londrina ficou em 2020?",
"Na primeira fase ficou em 6 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Rio Branco ficou em 2020?",
"Na primeira fase ficou em 7 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Paraná ficou em 2020?",
"Na primeira fase ficou em 8 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Cascavel CR ficou em 2020?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Toledo ficou em 2020?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o PSTC ficou em 2020?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o União ficou em 2020?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Em que posição o Toledo ficou em 2019?",
"Na fase da primeira taça jogou no grupo A, e ficou em 1 colocado. Avançou até a grande final, porem ficou com o titulo de vice",
"Em que posição o FC Cascavel ficou em 2019?",
"Na fase da primeira taça jogou no grupo B, e ficou em 1 colocado.  Avançou até as quartas de final, onde foi eliminado",
"Em que posição o Operário ficou em 2019?",
"Na fase da primeira taça jogou no grupo A, e ficou em 2 colocado.  Avançou até as quartas de final, onde foi eliminado",
"Em que posição o Coritiba ficou em 2019?",
"Na fase da primeira taça jogou no grupo B, e ficou em 2 colocado. Avançou até as semi-finais, onde foi eliminado",
"Em que posição o Maringá ficou em 2019?",
"Na fase da primeira taça jogou no grupo A, e ficou em 3 colocado. Não se classificando para as fases seguintes",
"Em que posição o Paraná ficou em 2019?",
"Na fase da primeira taça jogou no grupo B, e ficou em 3 colocado. Não se classificando para as fases seguintes",
"Em que posição o Londrina ficou em 2019?",
"Na fase da primeira taça jogou no grupo A, e ficou em 4 colocado. Não se classificando para as fases seguintes",
"Em que posição o Cianorte ficou em 2019?",
"Na fase da primeira taça jogou no grupo B, e ficou em 4 colocado. Não se classificando para as fases seguintes",
"Em que posição o Athletico Paranaense ficou em 2019?",
"Na fase da primeira taça jogou no grupo A, e ficou em 5 colocado. Não se classificando para as fases seguintes",
"Em que posição o Cascavel CR ficou em 2019?",
"Na fase da primeira taça jogou no grupo B, e ficou em 5 colocado. Não se classificando para as fases seguintes",
"Em que posição o Foz do Iguaçu ficou em 2019?",
"Na fase da primeira taça jogou no grupo A, e ficou em 6 colocado. Não se classificando para as fases seguintes",
"Em que posição o Rio Branco ficou em 2019?",
"Na fase da primeira taça jogou no grupo B, e ficou em 6 colocado. Não se classificando para as fases seguintes",
"Em que posição o Foz do Iguaçu ficou em 2018?",
"Na fase da primeira taça jogou no grupo A, e ficou em 1 colocado.  Avançou até as quartas de final, onde foi eliminado",
"Em que posição o Athletico Paranaense ficou em 2018?",
"Na fase da primeira taça jogou no grupo B, e ficou em 1 colocado. Avançou até a grande final, onde se consagrou campeão",
"Em que posição o Coritiba ficou em 2018?",
"Na fase da primeira taça jogou no grupo A, e ficou em 2 colocado. Avançou até a grande final, porem ficou com o titulo de vice",
"Em que posição o Rio Branco ficou em 2018?",
"Na fase da primeira taça jogou no grupo B, e ficou em 2 colocado. Avançou até as semi-finais, onde foi eliminado",
"Em que posição o FC Cascavel ficou em 2018?",
"Na fase da primeira taça jogou no grupo A, e ficou em 3 colocado. Não se classificando para as fases seguintes",
"Em que posição o Londrina ficou em 2018?",
"Na fase da primeira taça jogou no grupo B, e ficou em 3 colocado. Não se classificando para as fases seguintes",
"Em que posição o Cianorte ficou em 2018?",
"Na fase da primeira taça jogou no grupo A, e ficou em 4 colocado. Não se classificando para as fases seguintes",
"Em que posição o Toledo ficou em 2018?",
"Na fase da primeira taça jogou no grupo B, e ficou em 4 colocado. Não se classificando para as fases seguintes",
"Em que posição o Maringá ficou em 2018?",
"Na fase da primeira taça jogou no grupo A, e ficou em 5 colocado. Não se classificando para as fases seguintes",
"Em que posição o União ficou em 2018?",
"Na fase da primeira taça jogou no grupo B, e ficou em 5 colocado. Não se classificando para as fases seguintes",
"Em que posição o Paraná ficou em 2018?",
"Na fase da primeira taça jogou no grupo A, e ficou em 6 colocado. Não se classificando para as fases seguintes",
"Em que posição o Prudentópolis ficou em 2018?",
"Na fase da primeira taça jogou no grupo B, e ficou em 6 colocado. Não se classificando para as fases seguintes",
"Em que posição o Paraná ficou em 2017?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Coritiba ficou em 2017?",
"Na primeira fase ficou em 2 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",
"Em que posição o Cianorte ficou em 2017?",
"Na primeira fase ficou em 3 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Londrina ficou em 2017?",
"Na primeira fase ficou em 4 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Prudentópolis ficou em 2017?",
"Na primeira fase ficou em 5 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o FC Cascavel ficou em 2017?",
"Na primeira fase ficou em 6 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Athletico Paranaense ficou em 2017?",
"Na primeira fase ficou em 7 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o Rio Branco ficou em 2017?",
"Na primeira fase ficou em 8 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Foz do Iguaçu ficou em 2017?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Toledo ficou em 2017?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o PSTC ficou em 2017?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o J.Malucelli ficou em 2017?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Em que posição o Paraná ficou em 2016?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o J.Malucelli ficou em 2016?",
"Na primeira fase ficou em 2 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Coritiba ficou em 2016?",
"Na primeira fase ficou em 3 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o Athletico Paranaense ficou em 2016?",
"Na primeira fase ficou em 4 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",
"Em que posição o Londrina ficou em 2016?",
"Na primeira fase ficou em 5 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Toledo ficou em 2016?",
"Na primeira fase ficou em 6 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o PSTC ficou em 2016?",
"Na primeira fase ficou em 7 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Foz do Iguaçu ficou em 2016?",
"Na primeira fase ficou em 8 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o FC Cascavel ficou em 2016?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Rio Branco ficou em 2016?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o Operário ficou em 2016?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o Maringá ficou em 2016?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Em que posição o Coritiba ficou em 2015?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o J.Malucelli ficou em 2015?",
"Na primeira fase ficou em 2 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Operário ficou em 2015?",
"Na primeira fase ficou em 3 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",
"Em que posição o Maringá ficou em 2015?",
"Na primeira fase ficou em 4 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Londrina ficou em 2015?",
"Na primeira fase ficou em 5 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Paraná ficou em 2015?",
"Na primeira fase ficou em 6 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Foz do Iguaçu ficou em 2015?",
"Na primeira fase ficou em 7 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o FC Cascavel ficou em 2015?",
"Na primeira fase ficou em 8 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Athletico Paranaense ficou em 2015?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Rio Branco ficou em 2015?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o Nacional AC ficou em 2015?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o Prudentópolis ficou em 2015?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Em que posição o Paraná ficou em 2014?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Coritiba ficou em 2014?",
"Na primeira fase ficou em 2 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Maringá ficou em 2014?",
"Na primeira fase ficou em 3 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o Londrina ficou em 2014?",
"Na primeira fase ficou em 4 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",
"Em que posição o J.Malucelli ficou em 2014?",
"Na primeira fase ficou em 5 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Prudentópolis ficou em 2014?",
"Na primeira fase ficou em 6 colocado, então não se classificou para a segunda fase",
"Em que posição o Rio Branco ficou em 2014?",
"Na primeira fase ficou em 7 colocado, ja na segunda fase avançou até  as quartas de final, onde foi eliminado",
"Em que posição o Athletico Paranaense ficou em 2014?",
"Na primeira fase ficou em 8 colocado, ja na segunda fase avançou até as semi-finais, onde foi eliminado",
"Em que posição o Cianorte ficou em 2014?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Operário ficou em 2014?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o Arapongas EC ficou em 2014?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o Toledo ficou em 2014?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Em que posição o Coritiba ficou em 2013?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",
"Em que posição o Londrina ficou em 2013?",
"Na primeira fase ficou em 2 colocado, então não se classificou para a segunda fase",
"Em que posição o Paraná ficou em 2013?",
"Na primeira fase ficou em 3 colocado, então não se classificou para a segunda fase",
"Em que posição o J.Malucelli ficou em 2013?",
"Na primeira fase ficou em 4 colocado, então não se classificou para a segunda fase",
"Em que posição o Athletico Paranaense ficou em 2013?",
"Na primeira fase ficou em 5 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o Arapongas EC ficou em 2013?",
"Na primeira fase ficou em 6 colocado, então não se classificou para a segunda fase",
"Em que posição o AC Paranavai ficou em 2013?",
"Na primeira fase ficou em 7 colocado, então não se classificou para a segunda fase",
"Em que posição o Toledo ficou em 2013?",
"Na primeira fase ficou em 8 colocado, então não se classificou para a segunda fase",
"Em que posição o Operário ficou em 2013?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Cianorte ficou em 2013?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o Rio Branco ficou em 2013?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o Nacional AC ficou em 2013?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Em que posição o Athletico Paranaense ficou em 2012?",
"Na primeira fase ficou em 1 colocado, ja na segunda fase avançou até A final, onde foi eliminado",
"Em que posição o Coritiba ficou em 2012?",
"Na primeira fase ficou em 2 colocado, ja na segunda fase avançou até A final, onde se consagrou campeão",
"Em que posição o Cianorte ficou em 2012?",
"Na primeira fase ficou em 3 colocado, então não se classificou para a segunda fase",
"Em que posição o Arapongas EC ficou em 2012?",
"Na primeira fase ficou em 4 colocado, então não se classificou para a segunda fase",
"Em que posição o Toledo ficou em 2012?",
"Na primeira fase ficou em 5 colocado, então não se classificou para a segunda fase",
"Em que posição o Rio Branco ficou em 2012?",
"Na primeira fase ficou em 6 colocado, então não se classificou para a segunda fase",
"Em que posição o Londrina ficou em 2012?",
"Na primeira fase ficou em 7 colocado, então não se classificou para a segunda fase",
"Em que posição o J.Malucelli ficou em 2012?",
"Na primeira fase ficou em 8 colocado, então não se classificou para a segunda fase",
"Em que posição o Roma Apucarana ficou em 2012?",
"Na primeira fase ficou em 9 colocado, então não se classificou para a segunda fase",
"Em que posição o Operário ficou em 2012?",
"Na primeira fase ficou em 10 colocado, então não se classificou para a segunda fase",
"Em que posição o AC Paranavai ficou em 2012?",
"Na primeira fase ficou em 11 colocado, então não se classificou para a segunda fase",
"Em que posição o Iraty SC ficou em 2012?",
"Na primeira fase ficou em 12 colocado, então não se classificou para a segunda fase",
"Quem foi campeão em 2023?",
"O Athletico Paranaense levou o titulo no campeonato de 2023",
"Quem foi campeão em 2022?",
"O Coritiba levou o titulo no campeonato de 2022",
"Quem foi campeão em 2022?",
"O Londrina levou o titulo no campeonato de 2022",
"Quem foi campeão em 2020?",
"O Athletico Paranaense levou o titulo no campeonato de 2020",
"Quem foi campeão em 2019?",
"O Athletico Paranaense levou o titulo no campeonato de 2019",
"Quem foi campeão em 2018?",
"O Athletico Paranaense levou o titulo no campeonato de 2018",
"Quem foi campeão em 2017?",
"O Coritiba levou o titulo no campeonato de 2017",
"Quem foi campeão em 2016?",
"O Athletico Paranaense levou o titulo no campeonato de 2016",
"Quem foi campeão em 2015?",
"O Operário levou o titulo no campeonato de 2015",
"Quem foi campeão em 2014?",
"O Londrina levou o titulo no campeonato de 2014",
"Quem foi campeão em 2013?",
"O Coritiba levou o titulo no campeonato de 2013",
"Quem foi campeão em 2012?",
"O Coritiba levou o titulo no campeonato de 2012",
"Quem foi rebaixado em 2023?",
"Os clubes Rio Branco e Foz do Iguaçu foram rebaixados na edição de 2023 ",
"Quem foi rebaixado em 2022?",
"Os clubes União e Paraná foram rebaixados na edição de 2022 ",
"Quem foi rebaixado em 2022?",
"Os clubes Toledo e Cascavel CR foram rebaixados na edição de 2022 ",      
"Quem foi rebaixado em 2020?",
"Os clubes PSTC e União foram rebaixados na edição de 2020 ",
"Quem foi rebaixado em 2019?",
"Os clubes Maringá e Foz do Iguaçu foram rebaixados na edição de 2019 ",
"Quem foi rebaixado em 2018?",
"Os clubes União e Prudentópolis foram rebaixados na edição de 2018 ",
"Quem foi rebaixado em 2017?",
"Os clubes PSTC e J.Malucelli foram rebaixados na edição de 2017 ",
"Quem foi rebaixado em 2016?",
"Os clubes Operário e Maringá foram rebaixados na edição de 2016 ",
"Quem foi rebaixado em 2015?",
"Os clubes Nacional AC e Prudentópolis foram rebaixados na edição de 2015 ",
"Quem foi rebaixado em 2014?",
"Os clubes Arapongas EC e Toledo foram rebaixados na edição de 2014 ",
"Quem foi rebaixado em 2013?",
"Os clubes AC Paranavai e Nacional AC foram rebaixados na edição de 2013 ",
"Quem foi rebaixado em 2012?",
"Os clubes Roma Apucarana e Iraty SC foram rebaixados na edição de 2012 ",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Maringá tem?",
"O Maringá ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o FC Cascavel tem?",
"O FC Cascavel ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Aruko SB tem?",
"O Aruko SB ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o São-Joseense tem?",
"O São-Joseense ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Azuriz tem?",
"O Azuriz ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Foz do Iguaçu tem?",
"O Foz do Iguaçu ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Maringá tem?",
"O Maringá ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o FC Cascavel tem?",
"O FC Cascavel ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o São-Joseense tem?",
"O São-Joseense ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Azuriz tem?",
"O Azuriz ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o União tem?",
"O União ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o FC Cascavel tem?",
"O FC Cascavel ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o Maringá tem?",
"O Maringá ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Azuriz tem?",
"O Azuriz ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Toledo tem?",
"O Toledo ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Cascavel CR tem?",
"O Cascavel CR ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o FC Cascavel tem?",
"O FC Cascavel ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o Cascavel CR tem?",
"O Cascavel CR ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Toledo tem?",
"O Toledo ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o PSTC tem?",
"O PSTC ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o União tem?",
"O União ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Toledo tem?",
"O Toledo ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o FC Cascavel tem?",
"O FC Cascavel ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Maringá tem?",
"O Maringá ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Cascavel CR tem?",
"O Cascavel CR ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Foz do Iguaçu tem?",
"O Foz do Iguaçu ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Foz do Iguaçu tem?",
"O Foz do Iguaçu ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o FC Cascavel tem?",
"O FC Cascavel ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Toledo tem?",
"O Toledo ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Maringá tem?",
"O Maringá ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o União tem?",
"O União ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o Prudentópolis tem?",
"O Prudentópolis ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Prudentópolis tem?",
"O Prudentópolis ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o FC Cascavel tem?",
"O FC Cascavel ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Foz do Iguaçu tem?",
"O Foz do Iguaçu ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Toledo tem?",
"O Toledo ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o PSTC tem?",
"O PSTC ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o J.Malucelli tem?",
"O J.Malucelli ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o J.Malucelli tem?",
"O J.Malucelli ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Toledo tem?",
"O Toledo ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o PSTC tem?",
"O PSTC ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Foz do Iguaçu tem?",
"O Foz do Iguaçu ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o FC Cascavel tem?",
"O FC Cascavel ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Maringá tem?",
"O Maringá ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o J.Malucelli tem?",
"O J.Malucelli ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Maringá tem?",
"O Maringá ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o Foz do Iguaçu tem?",
"O Foz do Iguaçu ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o FC Cascavel tem?",
"O FC Cascavel ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Nacional AC tem?",
"O Nacional AC ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Prudentópolis tem?",
"O Prudentópolis ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Maringá tem?",
"O Maringá ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o J.Malucelli tem?",
"O J.Malucelli ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Prudentópolis tem?",
"O Prudentópolis ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Arapongas EC tem?",
"O Arapongas EC ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Toledo tem?",
"O Toledo ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o Paraná tem?",
"Atualmente o Paraná acumula 7 titulos de campeão paranaense",
"Quantos titulos o J.Malucelli tem?",
"O J.Malucelli ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Arapongas EC tem?",
"O Arapongas EC ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o AC Paranavai tem?",
"O AC Paranavai possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Toledo tem?",
"O Toledo ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Nacional AC tem?",
"O Nacional AC ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Athletico Paranaense tem?",
"Atualmente o Athletico Paranaense acumula 27 titulos de campeão paranaense",
"Quantos titulos o Coritiba tem?",
"Atualmente o Coritiba acumula 39 titulos de campeão paranaense",
"Quantos titulos o Cianorte tem?",
"O Cianorte ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Arapongas EC tem?",
"O Arapongas EC ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Toledo tem?",
"O Toledo ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Rio Branco tem?",
"O Rio Branco ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Londrina tem?",
"Atualmente o Londrina acumula 5 titulos de campeão paranaense",
"Quantos titulos o J.Malucelli tem?",
"O J.Malucelli ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Roma Apucarana tem?",
"O Roma Apucarana ainda não ganhou nenhuma edição do campeonato paranaense",
"Quantos titulos o Operário tem?",
"O Operário possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o AC Paranavai tem?",
"O AC Paranavai possui apenas 1 titulo de campeão paranaense",
"Quantos titulos o Iraty SC tem?",
"O Iraty SC possui apenas 1 titulo de campeão paranaense",
"O Foz do Iguaçu cedia seus jogos como mandante no Estadio do ABC, que tem uma capacidade de publico de 6969",
"Qual é o estádio do Toledo?",
"O Toledo cedia seus jogos como mandante no Municipal 14 de Dezembro, que tem uma capacidade de publico de 15280",
"Qual é o estádio do PSTC?",
"O PSTC cedia seus jogos como mandante no Estádio Ubirajara Medeiros, que tem uma capacidade de publico de 3500",
"Qual é o estádio do J.Malucelli?",
"O J.Malucelli cedia seus jogos como mandante no Ecoestádio Janguito Malucelli, que tem uma capacidade de publico de 4200",
"Qual é o estádio do Paraná?",
"O Paraná cedia seus jogos como mandante no Durival Britto e Silva(Vila Capanema), que tem uma capacidade de publico de 20083",
"Qual é o estádio do J.Malucelli?",
"O J.Malucelli cedia seus jogos como mandante no Ecoestádio Janguito Malucelli, que tem uma capacidade de publico de 4200",
"Qual é o estádio do Coritiba?",
"O Coritiba cedia seus jogos como mandante no Major Antônio Couto Pereira, que tem uma capacidade de publico de 40512",
"Qual é o estádio do Athletico Paranaense?",
"O Athletico Paranaense cedia seus jogos como mandante no Joaquin Américo Guimarães(Arena da Baixada), que tem uma capacidade de publico de 42372",
"Qual é o estádio do Londrina?",
"O Londrina cedia seus jogos como mandante no Municipal Jacy Scaff(Estadio do Cafe), que tem uma capacidade de publico de 30000",
"Qual é o estádio do Toledo?",
"O Toledo cedia seus jogos como mandante no Municipal 14 de Dezembro, que tem uma capacidade de publico de 15280",
"Qual é o estádio do PSTC?",
"O PSTC cedia seus jogos como mandante no Estádio Ubirajara Medeiros, que tem uma capacidade de publico de 3500",
"Qual é o estádio do Foz do Iguaçu?",
"O Foz do Iguaçu cedia seus jogos como mandante no Estadio do ABC, que tem uma capacidade de publico de 6969",
"Qual é o estádio do FC Cascavel?",
"O FC Cascavel cedia seus jogos como mandante no Olimpico Regional Arnaldo Busatto, que tem uma capacidade de publico de 28125",
"Qual é o estádio do Rio Branco?",
"O Rio Branco cedia seus jogos como mandante no Nelson Medrado Dias(Estradinha), que tem uma capacidade de publico de 4500",
"Qual é o estádio do Operário?",
"O Operário cedia seus jogos como mandante no Germano Kruger, que tem uma capacidade de publico de 10362",
"Qual é o estádio do Maringá?",
"O Maringá cedia seus jogos como mandante no Regional Willie Davids, que tem uma capacidade de publico de 21000",
"Qual é o estádio do Coritiba?",
"O Coritiba cedia seus jogos como mandante no Major Antônio Couto Pereira, que tem uma capacidade de publico de 40512",
"Qual é o estádio do J.Malucelli?",
"O J.Malucelli cedia seus jogos como mandante no Ecoestádio Janguito Malucelli, que tem uma capacidade de publico de 4200",
"Qual é o estádio do Operário?",
"O Operário cedia seus jogos como mandante no Germano Kruger, que tem uma capacidade de publico de 10362",
"Qual é o estádio do Maringá?",
"O Maringá cedia seus jogos como mandante no Regional Willie Davids, que tem uma capacidade de publico de 21000",
"Qual é o estádio do Londrina?",
"O Londrina cedia seus jogos como mandante no Municipal Jacy Scaff(Estadio do Cafe), que tem uma capacidade de publico de 30000",
"Qual é o estádio do Paraná?",
"O Paraná cedia seus jogos como mandante no Durival Britto e Silva(Vila Capanema), que tem uma capacidade de publico de 20083",
"Qual é o estádio do Foz do Iguaçu?",
"O Foz do Iguaçu cedia seus jogos como mandante no Estadio do ABC, que tem uma capacidade de publico de 6969",
"Qual é o estádio do FC Cascavel?",
"O FC Cascavel cedia seus jogos como mandante no Olimpico Regional Arnaldo Busatto, que tem uma capacidade de publico de 28125",
"Qual é o estádio do Athletico Paranaense?",
"O Athletico Paranaense cedia seus jogos como mandante no Joaquin Américo Guimarães(Arena da Baixada), que tem uma capacidade de publico de 42372",
"Qual é o estádio do Rio Branco?",
"O Rio Branco cedia seus jogos como mandante no Nelson Medrado Dias(Estradinha), que tem uma capacidade de publico de 4500",
"Qual é o estádio do Nacional AC?",
"O Nacional AC cedia seus jogos como mandante no Erich George, que tem uma capacidade de publico de 2050",
"Qual é o estádio do Prudentópolis?",
"O Prudentópolis cedia seus jogos como mandante no Estádio Newton Agibert, que tem uma capacidade de publico de 5000",
"Qual é o estádio do Paraná?",
"O Paraná cedia seus jogos como mandante no Durival Britto e Silva(Vila Capanema), que tem uma capacidade de publico de 20083",
"Qual é o estádio do Coritiba?",
"O Coritiba cedia seus jogos como mandante no Major Antônio Couto Pereira, que tem uma capacidade de publico de 40512",
"Qual é o estádio do Maringá?",
"O Maringá cedia seus jogos como mandante no Regional Willie Davids, que tem uma capacidade de publico de 21000",
"Qual é o estádio do Londrina?",
"O Londrina cedia seus jogos como mandante no Municipal Jacy Scaff(Estadio do Cafe), que tem uma capacidade de publico de 30000",
"Qual é o estádio do J.Malucelli?",
"O J.Malucelli cedia seus jogos como mandante no Ecoestádio Janguito Malucelli, que tem uma capacidade de publico de 4200",
"Qual é o estádio do Prudentópolis?",
"O Prudentópolis cedia seus jogos como mandante no Estádio Newton Agibert, que tem uma capacidade de publico de 5000",
"Qual é o estádio do Rio Branco?",
"O Rio Branco cedia seus jogos como mandante no Nelson Medrado Dias(Estradinha), que tem uma capacidade de publico de 4500",
"Qual é o estádio do Athletico Paranaense?",
"O Athletico Paranaense cedia seus jogos como mandante no Joaquin Américo Guimarães(Arena da Baixada), que tem uma capacidade de publico de 42372",
"Qual é o estádio do Cianorte?",
"O Cianorte cedia seus jogos como mandante no Olimpico Albino Turbay, que tem uma capacidade de publico de 3000",
"Qual é o estádio do Operário?",
"O Operário cedia seus jogos como mandante no Germano Kruger, que tem uma capacidade de publico de 10362",
"Qual é o estádio do Arapongas EC?",
"O Arapongas EC cedia seus jogos como mandante no Estádio dos Pássaros, que tem uma capacidade de publico de 15000",
"Qual é o estádio do Toledo?",
"O Toledo cedia seus jogos como mandante no Municipal 14 de Dezembro, que tem uma capacidade de publico de 15280",
"Qual é o estádio do Coritiba?",
"O Coritiba cedia seus jogos como mandante no Major Antônio Couto Pereira, que tem uma capacidade de publico de 40512",
"Qual é o estádio do Londrina?",
"O Londrina cedia seus jogos como mandante no Municipal Jacy Scaff(Estadio do Cafe), que tem uma capacidade de publico de 30000",
"Qual é o estádio do Paraná?",
"O Paraná cedia seus jogos como mandante no Durival Britto e Silva(Vila Capanema), que tem uma capacidade de publico de 20083",
"Qual é o estádio do J.Malucelli?",
"O J.Malucelli cedia seus jogos como mandante no Ecoestádio Janguito Malucelli, que tem uma capacidade de publico de 4200",
"Qual é o estádio do Athletico Paranaense?",
"O Athletico Paranaense cedia seus jogos como mandante no Joaquin Américo Guimarães(Arena da Baixada), que tem uma capacidade de publico de 42372",
"Qual é o estádio do Arapongas EC?",
"O Arapongas EC cedia seus jogos como mandante no Estádio dos Pássaros, que tem uma capacidade de publico de 15000",
"Qual é o estádio do AC Paranavai?",
"O AC Paranavai cedia seus jogos como mandante no Estádio Municipal Dr. Waldemiro Wagner, que tem uma capacidade de publico de 25000",
"Qual é o estádio do Toledo?",
"O Toledo cedia seus jogos como mandante no Municipal 14 de Dezembro, que tem uma capacidade de publico de 15280",
"Qual é o estádio do Operário?",
"O Operário cedia seus jogos como mandante no Germano Kruger, que tem uma capacidade de publico de 10362",
"Qual é o estádio do Cianorte?",
"O Cianorte cedia seus jogos como mandante no Olimpico Albino Turbay, que tem uma capacidade de publico de 3000",
"Qual é o estádio do Rio Branco?",
"O Rio Branco cedia seus jogos como mandante no Nelson Medrado Dias(Estradinha), que tem uma capacidade de publico de 4500",
"Qual é o estádio do Nacional AC?",
"O Nacional AC cedia seus jogos como mandante no Erich George, que tem uma capacidade de publico de 2050",
"Qual é o estádio do Athletico Paranaense?",
"O Athletico Paranaense cedia seus jogos como mandante no Joaquin Américo Guimarães(Arena da Baixada), que tem uma capacidade de publico de 42372",
"Qual é o estádio do Coritiba?",
"O Coritiba cedia seus jogos como mandante no Major Antônio Couto Pereira, que tem uma capacidade de publico de 40512",
"Qual é o estádio do Cianorte?",
"O Cianorte cedia seus jogos como mandante no Olimpico Albino Turbay, que tem uma capacidade de publico de 3000",
"Qual é o estádio do Arapongas EC?",
"O Arapongas EC cedia seus jogos como mandante no Estádio dos Pássaros, que tem uma capacidade de publico de 15000",
"Qual é o estádio do Toledo?",
"O Toledo cedia seus jogos como mandante no Municipal 14 de Dezembro, que tem uma capacidade de publico de 15280",
"Qual é o estádio do Rio Branco?",
"O Rio Branco cedia seus jogos como mandante no Nelson Medrado Dias(Estradinha), que tem uma capacidade de publico de 4500",
"Qual é o estádio do Londrina?",
"O Londrina cedia seus jogos como mandante no Municipal Jacy Scaff(Estadio do Cafe), que tem uma capacidade de publico de 30000",
"Qual é o estádio do J.Malucelli?",
"O J.Malucelli cedia seus jogos como mandante no Ecoestádio Janguito Malucelli, que tem uma capacidade de publico de 4200",
"Qual é o estádio do Roma Apucarana?",
"O Roma Apucarana cedia seus jogos como mandante no Olímpio Barreto, que tem uma capacidade de publico de 10000",
"Qual é o estádio do Operário?",
"O Operário cedia seus jogos como mandante no Germano Kruger, que tem uma capacidade de publico de 10362",
"Qual é o estádio do AC Paranavai?",
"O AC Paranavai cedia seus jogos como mandante no Estádio Municipal Dr. Waldemiro Wagner, que tem uma capacidade de publico de 25000",
"Qual é o estádio do Iraty SC?",
"O Iraty SC cedia seus jogos como mandante no   Estádio Coronel Emílio Gomes, que tem uma capacidade de publico de 8000",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Maringá?",
"O Maringá tem como casa a cidade de Maringá",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o FC Cascavel?",
"O FC Cascavel tem como casa a cidade de Cascavel",
"De qual cidade é o Aruko SB?",
"O Aruko SB tem como casa a cidade de Maringá",
"De qual cidade é o São-Joseense?",
"O São-Joseense tem como casa a cidade de São José dos Pinhais",
"De qual cidade é o Azuriz?",
"O Azuriz tem como casa a cidade de Pato Branco",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Foz do Iguaçu?",
"O Foz do Iguaçu tem como casa a cidade de Foz do Iguaçu",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Maringá?",
"O Maringá tem como casa a cidade de Maringá",
"De qual cidade é o FC Cascavel?",
"O FC Cascavel tem como casa a cidade de Cascavel",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o São-Joseense?",
"O São-Joseense tem como casa a cidade de São José dos Pinhais",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Azuriz?",
"O Azuriz tem como casa a cidade de Pato Branco",
"De qual cidade é o União?",
"O União tem como casa a cidade de Francisco Beltrão",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o FC Cascavel?",
"O FC Cascavel tem como casa a cidade de Cascavel",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o Maringá?",
"O Maringá tem como casa a cidade de Maringá",
"De qual cidade é o Azuriz?",
"O Azuriz tem como casa a cidade de Pato Branco",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Toledo?",
"O Toledo tem como casa a cidade de Toledo",
"De qual cidade é o Cascavel CR?",
"O Cascavel CR tem como casa a cidade de Cascavel",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o FC Cascavel?",
"O FC Cascavel tem como casa a cidade de Cascavel",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o Cascavel CR?",
"O Cascavel CR tem como casa a cidade de Cascavel",
"De qual cidade é o Toledo?",
"O Toledo tem como casa a cidade de Toledo",
"De qual cidade é o PSTC?",
"O PSTC tem como casa a cidade de Cornélio Procópio",
"De qual cidade é o União?",
"O União tem como casa a cidade de Francisco Beltrão",
"De qual cidade é o Toledo?",
"O Toledo tem como casa a cidade de Toledo",
"De qual cidade é o FC Cascavel?",
"O FC Cascavel tem como casa a cidade de Cascavel",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Maringá?",
"O Maringá tem como casa a cidade de Maringá",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Cascavel CR?",
"O Cascavel CR tem como casa a cidade de Cascavel",
"De qual cidade é o Foz do Iguaçu?",
"O Foz do Iguaçu tem como casa a cidade de Foz do Iguaçu",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Foz do Iguaçu?",
"O Foz do Iguaçu tem como casa a cidade de Foz do Iguaçu",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o FC Cascavel?",
"O FC Cascavel tem como casa a cidade de Cascavel",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o Toledo?",
"O Toledo tem como casa a cidade de Toledo",
"De qual cidade é o Maringá?",
"O Maringá tem como casa a cidade de Maringá",
"De qual cidade é o União?",
"O União tem como casa a cidade de Francisco Beltrão",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o Prudentópolis?",
"O Prudentópolis tem como casa a cidade de Prudentópolis",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Prudentópolis?",
"O Prudentópolis tem como casa a cidade de Prudentópolis",
"De qual cidade é o FC Cascavel?",
"O FC Cascavel tem como casa a cidade de Cascavel",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Foz do Iguaçu?",
"O Foz do Iguaçu tem como casa a cidade de Foz do Iguaçu",
"De qual cidade é o Toledo?",
"O Toledo tem como casa a cidade de Toledo",
"De qual cidade é o PSTC?",
"O PSTC tem como casa a cidade de Cornélio Procópio",
"De qual cidade é o J.Malucelli?",
"O J.Malucelli tem como casa a cidade de Curitiba",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o J.Malucelli?",
"O J.Malucelli tem como casa a cidade de Curitiba",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Toledo?",
"O Toledo tem como casa a cidade de Toledo",
"De qual cidade é o PSTC?",
"O PSTC tem como casa a cidade de Cornélio Procópio",
"De qual cidade é o Foz do Iguaçu?",
"O Foz do Iguaçu tem como casa a cidade de Foz do Iguaçu",
"De qual cidade é o FC Cascavel?",
"O FC Cascavel tem como casa a cidade de Cascavel",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o Maringá?",
"O Maringá tem como casa a cidade de Maringá",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o J.Malucelli?",
"O J.Malucelli tem como casa a cidade de Curitiba",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o Maringá?",
"O Maringá tem como casa a cidade de Maringá",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o Foz do Iguaçu?",
"O Foz do Iguaçu tem como casa a cidade de Foz do Iguaçu",
"De qual cidade é o FC Cascavel?",
"O FC Cascavel tem como casa a cidade de Cascavel",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Nacional AC?",
"O Nacional AC tem como casa a cidade de Rolândia",
"De qual cidade é o Prudentópolis?",
"O Prudentópolis tem como casa a cidade de Prudentópolis",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Maringá?",
"O Maringá tem como casa a cidade de Maringá",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o J.Malucelli?",
"O J.Malucelli tem como casa a cidade de Curitiba",
"De qual cidade é o Prudentópolis?",
"O Prudentópolis tem como casa a cidade de Prudentópolis",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o Arapongas EC?",
"O Arapongas EC tem como casa a cidade de Arapongas",
"De qual cidade é o Toledo?",
"O Toledo tem como casa a cidade de Toledo",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o Paraná?",
"O Paraná tem como casa a cidade de Curitiba",
"De qual cidade é o J.Malucelli?",
"O J.Malucelli tem como casa a cidade de Curitiba",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Arapongas EC?",
"O Arapongas EC tem como casa a cidade de Arapongas",
"De qual cidade é o AC Paranavai?",
"O AC Paranavai tem como casa a cidade de Paranavai",
"De qual cidade é o Toledo?",
"O Toledo tem como casa a cidade de Toledo",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Nacional AC?",
"O Nacional AC tem como casa a cidade de Rolândia",
"De qual cidade é o Athletico Paranaense?",
"O Athletico Paranaense tem como casa a cidade de Curitiba",
"De qual cidade é o Coritiba?",
"O Coritiba tem como casa a cidade de Curitiba",
"De qual cidade é o Cianorte?",
"O Cianorte tem como casa a cidade de Cianorte",
"De qual cidade é o Arapongas EC?",
"O Arapongas EC tem como casa a cidade de Arapongas",
"De qual cidade é o Toledo?",
"O Toledo tem como casa a cidade de Toledo",
"De qual cidade é o Rio Branco?",
"O Rio Branco tem como casa a cidade de Paranaguá",
"De qual cidade é o Londrina?",
"O Londrina tem como casa a cidade de Londrina",
"De qual cidade é o J.Malucelli?",
"O J.Malucelli tem como casa a cidade de Curitiba",
"De qual cidade é o Roma Apucarana?",
"O Roma Apucarana tem como casa a cidade de Apucarana",
"De qual cidade é o Operário?",
"O Operário tem como casa a cidade de Ponta Grossa",
"De qual cidade é o AC Paranavai?",
"O AC Paranavai tem como casa a cidade de Paranavai",
"De qual cidade é o Iraty SC?",
"O Iraty SC tem como casa a cidade de Irati",
"Qual foi o maior placar de 2023?",
"O maior placar foi de 5 a 0 do Athlético sobre o Azuriz",
"Qual foi o maior placar de 2022?",
"O maior placar foi de 5 a 0 do Maringá sobre o FC Cascavel",
"Qual foi o maior placar de 2022?",
"O maior placar foi de 9 a 0 do Operário sobre o Cascavel CR",
"Qual foi o maior placar de 2020?",
"O maior placar foi de 6 a 1 do Coritiba sobre o União",
"Qual foi o maior placar de 2019?",
"O maior placar foi de 8 a 2 do Athletico sobre o Toledo",
"Qual foi o maior placar de 2018?",
"O maior placar foi de 7 a 1 do Athletico sobre o Rio Branco",
"Qual foi o maior placar de 2017?",
"O maior placar foi de 5 a 0 do Paraná sobre o Foz do Iguaçu",
"Qual foi o maior placar de 2016?",
"O maior placar foi de 5 a 1 do Rio Branco sobre o Operário",
"Qual foi o maior placar de 2015?",
"O maior placar foi de 7 a 0 do Athletico sobre o Nacional",
"Qual foi o maior placar de 2014?",
"O maior placar foi de 4 a 0 do Parana sobre o Athletico",
"Qual foi o maior placar de 2013?",
"O maior placar foi de 7 a 0 do Coritiba sobre o Rio Branco",
"Qual foi o maior placar de 2012?",
"O maior placar foi de 5 a 0 do Athletico sobre o Operário",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Maringá?",
"O Maringá foi fundado em 2010, e tem 13 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o FC Cascavel?",
"O FC Cascavel foi fundado em 2008, e tem 15 anos de idade",
"Quantos anos tem o Aruko SB?",
"O Aruko SB foi fundado em 2020, e tem 3 anos de idade",
"Quantos anos tem o São-Joseense?",
"O São-Joseense foi fundado em 2015, e tem 8 anos de idade",
"Quantos anos tem o Azuriz?",
"O Azuriz foi fundado em 2018, e tem 5 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Foz do Iguaçu?",
"O Foz do Iguaçu foi fundado em 1996, e tem 27 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Maringá?",
"O Maringá foi fundado em 2010, e tem 13 anos de idade",
"Quantos anos tem o FC Cascavel?",
"O FC Cascavel foi fundado em 2008, e tem 15 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o São-Joseense?",
"O São-Joseense foi fundado em 2015, e tem 8 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Azuriz?",
"O Azuriz foi fundado em 2018, e tem 5 anos de idade",
"Quantos anos tem o União?",
"O União foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o FC Cascavel?",
"O FC Cascavel foi fundado em 2008, e tem 15 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o Maringá?",
"O Maringá foi fundado em 2010, e tem 13 anos de idade",
"Quantos anos tem o Azuriz?",
"O Azuriz foi fundado em 2018, e tem 5 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Toledo?",
"O Toledo foi fundado em 2004, e tem 19 anos de idade",
"Quantos anos tem o Cascavel CR?",
"O Cascavel CR foi fundado em 2001, e tem 22 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o FC Cascavel?",
"O FC Cascavel foi fundado em 2008, e tem 15 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o Cascavel CR?",
"O Cascavel CR foi fundado em 2001, e tem 22 anos de idade",
"Quantos anos tem o Toledo?",
"O Toledo foi fundado em 2004, e tem 19 anos de idade",
"Quantos anos tem o PSTC?",
"O PSTC foi fundado em 1994, e tem 29 anos de idade",
"Quantos anos tem o União?",
"O União foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Toledo?",
"O Toledo foi fundado em 2004, e tem 19 anos de idade",
"Quantos anos tem o FC Cascavel?",
"O FC Cascavel foi fundado em 2008, e tem 15 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Maringá?",
"O Maringá foi fundado em 2010, e tem 13 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Cascavel CR?",
"O Cascavel CR foi fundado em 2001, e tem 22 anos de idade",
"Quantos anos tem o Foz do Iguaçu?",
"O Foz do Iguaçu foi fundado em 1996, e tem 27 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Foz do Iguaçu?",
"O Foz do Iguaçu foi fundado em 1996, e tem 27 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o FC Cascavel?",
"O FC Cascavel foi fundado em 2008, e tem 15 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o Toledo?",
"O Toledo foi fundado em 2004, e tem 19 anos de idade",
"Quantos anos tem o Maringá?",
"O Maringá foi fundado em 2010, e tem 13 anos de idade",
"Quantos anos tem o União?",
"O União foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o Prudentópolis?",
"O Prudentópolis foi fundado em 2007, e tem 16 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Prudentópolis?",
"O Prudentópolis foi fundado em 2007, e tem 16 anos de idade",
"Quantos anos tem o FC Cascavel?",
"O FC Cascavel foi fundado em 2008, e tem 15 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Foz do Iguaçu?",
"O Foz do Iguaçu foi fundado em 1996, e tem 27 anos de idade",
"Quantos anos tem o Toledo?",
"O Toledo foi fundado em 2004, e tem 19 anos de idade",
"Quantos anos tem o PSTC?",
"O PSTC foi fundado em 1994, e tem 29 anos de idade",
"Quantos anos tem o J.Malucelli?",
"O J.Malucelli foi fundado em 1994, e tem 29 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o J.Malucelli?",
"O J.Malucelli foi fundado em 1994, e tem 29 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Toledo?",
"O Toledo foi fundado em 2004, e tem 19 anos de idade",
"Quantos anos tem o PSTC?",
"O PSTC foi fundado em 1994, e tem 29 anos de idade",
"Quantos anos tem o Foz do Iguaçu?",
"O Foz do Iguaçu foi fundado em 1996, e tem 27 anos de idade",
"Quantos anos tem o FC Cascavel?",
"O FC Cascavel foi fundado em 2008, e tem 15 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o Maringá?",
"O Maringá foi fundado em 2010, e tem 13 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o J.Malucelli?",
"O J.Malucelli foi fundado em 1994, e tem 29 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o Maringá?",
"O Maringá foi fundado em 2010, e tem 13 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o Foz do Iguaçu?",
"O Foz do Iguaçu foi fundado em 1996, e tem 27 anos de idade",
"Quantos anos tem o FC Cascavel?",
"O FC Cascavel foi fundado em 2008, e tem 15 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Nacional AC?",
"O Nacional AC foi fundado em 1947, e tem 76 anos de idade",
"Quantos anos tem o Prudentópolis?",
"O Prudentópolis foi fundado em 2007, e tem 16 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Maringá?",
"O Maringá foi fundado em 2010, e tem 13 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o J.Malucelli?",
"O J.Malucelli foi fundado em 1994, e tem 29 anos de idade",
"Quantos anos tem o Prudentópolis?",
"O Prudentópolis foi fundado em 2007, e tem 16 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o Arapongas EC?",
"O Arapongas EC foi fundado em 1974, e tem 49 anos de idade",
"Quantos anos tem o Toledo?",
"O Toledo foi fundado em 2004, e tem 19 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o Paraná?",
"O Paraná foi fundado em 1989, e tem 34 anos de idade",
"Quantos anos tem o J.Malucelli?",
"O J.Malucelli foi fundado em 1994, e tem 29 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Arapongas EC?",
"O Arapongas EC foi fundado em 1974, e tem 49 anos de idade",
"Quantos anos tem o AC Paranavai?",
"O AC Paranavai foi fundado em 1946, e tem 77 anos de idade",
"Quantos anos tem o Toledo?",
"O Toledo foi fundado em 2004, e tem 19 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Nacional AC?",
"O Nacional AC foi fundado em 1947, e tem 76 anos de idade",
"Quantos anos tem o Athletico Paranaense?",
"O Athletico Paranaense foi fundado em 1924, e tem 99 anos de idade",
"Quantos anos tem o Coritiba?",
"O Coritiba foi fundado em 1909, e tem 114 anos de idade",
"Quantos anos tem o Cianorte?",
"O Cianorte foi fundado em 2002, e tem 21 anos de idade",
"Quantos anos tem o Arapongas EC?",
"O Arapongas EC foi fundado em 1974, e tem 49 anos de idade",
"Quantos anos tem o Toledo?",
"O Toledo foi fundado em 2004, e tem 19 anos de idade",
"Quantos anos tem o Rio Branco?",
"O Rio Branco foi fundado em 1913, e tem 110 anos de idade",
"Quantos anos tem o Londrina?",
"O Londrina foi fundado em 1956, e tem 67 anos de idade",
"Quantos anos tem o J.Malucelli?",
"O J.Malucelli foi fundado em 1994, e tem 29 anos de idade",
"Quantos anos tem o Roma Apucarana?",
"O Roma Apucarana foi fundado em 2000, e tem 23 anos de idade",
"Quantos anos tem o Operário?",
"O Operário foi fundado em 1912, e tem 111 anos de idade",
"Quantos anos tem o AC Paranavai?",
"O AC Paranavai foi fundado em 1946, e tem 77 anos de idade",
"Quantos anos tem o Iraty SC?",
"O Iraty SC foi fundado em 1914, e tem 109 anos de idade",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Maringá participou do paranaense?",
"O Maringá ja participou de 8 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o FC Cascavel participou do paranaense?",
"O FC Cascavel ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Aruko SB participou do paranaense?",
"O Aruko SB ja participou de 1 edições do campeonato paranaense",
"Quantas vezes o São-Joseense participou do paranaense?",
"O São-Joseense ja participou de 1 edições do campeonato paranaense",
"Quantas vezes o Azuriz participou do paranaense?",
"O Azuriz ja participou de 2 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Foz do Iguaçu participou do paranaense?",
"O Foz do Iguaçu ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Maringá participou do paranaense?",
"O Maringá ja participou de 8 edições do campeonato paranaense",
"Quantas vezes o FC Cascavel participou do paranaense?",
"O FC Cascavel ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o São-Joseense participou do paranaense?",
"O São-Joseense ja participou de 1 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Azuriz participou do paranaense?",
"O Azuriz ja participou de 2 edições do campeonato paranaense",
"Quantas vezes o União participou do paranaense?",
"O União ja participou de 4 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o FC Cascavel participou do paranaense?",
"O FC Cascavel ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o Maringá participou do paranaense?",
"O Maringá ja participou de 8 edições do campeonato paranaense",
"Quantas vezes o Azuriz participou do paranaense?",
"O Azuriz ja participou de 2 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Toledo participou do paranaense?",
"O Toledo ja participou de 12 edições do campeonato paranaense",
"Quantas vezes o Cascavel CR participou do paranaense?",
"O Cascavel CR ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o FC Cascavel participou do paranaense?",
"O FC Cascavel ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o Cascavel CR participou do paranaense?",
"O Cascavel CR ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Toledo participou do paranaense?",
"O Toledo ja participou de 12 edições do campeonato paranaense",
"Quantas vezes o PSTC participou do paranaense?",
"O PSTC ja participou de 3 edições do campeonato paranaense",
"Quantas vezes o União participou do paranaense?",
"O União ja participou de 4 edições do campeonato paranaense",
"Quantas vezes o Toledo participou do paranaense?",
"O Toledo ja participou de 12 edições do campeonato paranaense",
"Quantas vezes o FC Cascavel participou do paranaense?",
"O FC Cascavel ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Maringá participou do paranaense?",
"O Maringá ja participou de 8 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Cascavel CR participou do paranaense?",
"O Cascavel CR ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Foz do Iguaçu participou do paranaense?",
"O Foz do Iguaçu ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Foz do Iguaçu participou do paranaense?",
"O Foz do Iguaçu ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o FC Cascavel participou do paranaense?",
"O FC Cascavel ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o Toledo participou do paranaense?",
"O Toledo ja participou de 12 edições do campeonato paranaense",
"Quantas vezes o Maringá participou do paranaense?",
"O Maringá ja participou de 8 edições do campeonato paranaense",
"Quantas vezes o União participou do paranaense?",
"O União ja participou de 4 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o Prudentópolis participou do paranaense?",
"O Prudentópolis ja participou de 5 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Prudentópolis participou do paranaense?",
"O Prudentópolis ja participou de 5 edições do campeonato paranaense",
"Quantas vezes o FC Cascavel participou do paranaense?",
"O FC Cascavel ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Foz do Iguaçu participou do paranaense?",
"O Foz do Iguaçu ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o Toledo participou do paranaense?",
"O Toledo ja participou de 12 edições do campeonato paranaense",
"Quantas vezes o PSTC participou do paranaense?",
"O PSTC ja participou de 3 edições do campeonato paranaense",
"Quantas vezes o J.Malucelli participou do paranaense?",
"O J.Malucelli ja participou de 10 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o J.Malucelli participou do paranaense?",
"O J.Malucelli ja participou de 10 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Toledo participou do paranaense?",
"O Toledo ja participou de 12 edições do campeonato paranaense",
"Quantas vezes o PSTC participou do paranaense?",
"O PSTC ja participou de 3 edições do campeonato paranaense",
"Quantas vezes o Foz do Iguaçu participou do paranaense?",
"O Foz do Iguaçu ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o FC Cascavel participou do paranaense?",
"O FC Cascavel ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o Maringá participou do paranaense?",
"O Maringá ja participou de 8 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o J.Malucelli participou do paranaense?",
"O J.Malucelli ja participou de 10 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o Maringá participou do paranaense?",
"O Maringá ja participou de 8 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o Foz do Iguaçu participou do paranaense?",
"O Foz do Iguaçu ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o FC Cascavel participou do paranaense?",
"O FC Cascavel ja participou de 9 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Nacional AC participou do paranaense?",
"O Nacional AC ja participou de 17 edições do campeonato paranaense",
"Quantas vezes o Prudentópolis participou do paranaense?",
"O Prudentópolis ja participou de 5 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Maringá participou do paranaense?",
"O Maringá ja participou de 8 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o J.Malucelli participou do paranaense?",
"O J.Malucelli ja participou de 10 edições do campeonato paranaense",
"Quantas vezes o Prudentópolis participou do paranaense?",
"O Prudentópolis ja participou de 5 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o Arapongas EC participou do paranaense?",
"O Arapongas EC ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o Toledo participou do paranaense?",
"O Toledo ja participou de 12 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o Paraná participou do paranaense?",
"O Paraná ja participou de 29 edições do campeonato paranaense",
"Quantas vezes o J.Malucelli participou do paranaense?",
"O J.Malucelli ja participou de 10 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Arapongas EC participou do paranaense?",
"O Arapongas EC ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o AC Paranavai participou do paranaense?",
"O AC Paranavai ja participou de 37 edições do campeonato paranaense",
"Quantas vezes o Toledo participou do paranaense?",
"O Toledo ja participou de 12 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Nacional AC participou do paranaense?",
"O Nacional AC ja participou de 17 edições do campeonato paranaense",
"Quantas vezes o Athletico Paranaense participou do paranaense?",
"O Athletico Paranaense ja participou de 88 edições do campeonato paranaense",
"Quantas vezes o Coritiba participou do paranaense?",
"O Coritiba ja participou de 99 edições do campeonato paranaense",
"Quantas vezes o Cianorte participou do paranaense?",
"O Cianorte ja participou de 18 edições do campeonato paranaense",
"Quantas vezes o Arapongas EC participou do paranaense?",
"O Arapongas EC ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o Toledo participou do paranaense?",
"O Toledo ja participou de 12 edições do campeonato paranaense",
"Quantas vezes o Rio Branco participou do paranaense?",
"O Rio Branco ja participou de 54 edições do campeonato paranaense",
"Quantas vezes o Londrina participou do paranaense?",
"O Londrina ja participou de 49 edições do campeonato paranaense",
"Quantas vezes o J.Malucelli participou do paranaense?",
"O J.Malucelli ja participou de 10 edições do campeonato paranaense",
"Quantas vezes o Roma Apucarana participou do paranaense?",
"O Roma Apucarana ja participou de 7 edições do campeonato paranaense",
"Quantas vezes o Operário participou do paranaense?",
"O Operário ja participou de 51 edições do campeonato paranaense",
"Quantas vezes o AC Paranavai participou do paranaense?",
"O AC Paranavai ja participou de 37 edições do campeonato paranaense",
"Quantas vezes o Iraty SC participou do paranaense?",
"O Iraty SC ja participou de 27 edições do campeonato paranaense",

])


